networks:
  app_network:
    driver: bridge

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    container_name: app1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - app_network
    container_name: app2

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - app_network
    container_name: app3

  nginx:
    build: ./nginx
    ports:
      - "80:80" 
    networks:
      - app_network
    depends_on:
      - app1
      - app2
      - app3
    container_name: nginx
